version: "3"
services:

  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
      - api
    ports:
      - 80:80
    networks:
      - webappnetwork
  client:
    image: webapp-client
    build: ./client
    # ports:
    #   - "3000:3000"
    working_dir: /client/src/app
    volumes:
      - ./client:/client/src/app
    depends_on:
      - api
    networks:
      - webappnetwork

  api:
    image: webapp-api
    build: ./api
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - db
    networks:
      - webappnetwork
    environment:
      WAIT_HOSTS: db:27017

  db:
    image: mongo:5.0
    volumes:
      - ./data-node:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - webappnetwork

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@db:27017/
    networks:
      - webappnetwork

networks:
  webappnetwork:
    driver: bridge
