version: "3"
services:
  client:
    image: webapp-client
    build: ./client
    ports:
      - "3000:3000"
    working_dir: /client/src/app
    volumes:
      - ./client:/client/src/app
    depends_on:
      - api
    networks:
      - webappnetwork

  api:
    image: webapp-api
    build: ./api
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - mongodb
    networks:
      - webappnetwork
    environment:
      WAIT_HOSTS: mongodb:27017

  mongodb:
    image: mongo
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth --smallfiles
    networks:
      - webappnetwork

networks:
  webappnetwork:
    driver: bridge
