#apiVersion: networking.k8s.io/v1
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: minimal-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: client
          servicePort: 3000
      - path: /api
        backend:
          serviceName: api
          servicePort: 9000
